// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHLXL5Uh4e889WaLKQbCAeSffsaxscF4',
    appId: '1:861491462844:web:c1570d1bb0f165a515c6b9',
    messagingSenderId: '861491462844',
    projectId: 'e-commerce-app-971e8',
    authDomain: 'e-commerce-app-971e8.firebaseapp.com',
    storageBucket: 'e-commerce-app-971e8.firebasestorage.app',
    measurementId: 'G-PQ48R0XDNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQ6D7D-FTjA7XiGdcvKFUZSQ1TRpnKcs',
    appId: '1:861491462844:android:bce4c44027e96aba15c6b9',
    messagingSenderId: '861491462844',
    projectId: 'e-commerce-app-971e8',
    storageBucket: 'e-commerce-app-971e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALr7TUSU222J7oV4k_rXlm_vxaaXjt1jg',
    appId: '1:861491462844:ios:a1a4d3dcbf114c9a15c6b9',
    messagingSenderId: '861491462844',
    projectId: 'e-commerce-app-971e8',
    storageBucket: 'e-commerce-app-971e8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALr7TUSU222J7oV4k_rXlm_vxaaXjt1jg',
    appId: '1:861491462844:ios:a1a4d3dcbf114c9a15c6b9',
    messagingSenderId: '861491462844',
    projectId: 'e-commerce-app-971e8',
    storageBucket: 'e-commerce-app-971e8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByHLXL5Uh4e889WaLKQbCAeSffsaxscF4',
    appId: '1:861491462844:web:e88bf16ab233c72415c6b9',
    messagingSenderId: '861491462844',
    projectId: 'e-commerce-app-971e8',
    authDomain: 'e-commerce-app-971e8.firebaseapp.com',
    storageBucket: 'e-commerce-app-971e8.firebasestorage.app',
    measurementId: 'G-1BYY18C443',
  );
}
